### ISSUE TITLE
test data need

### ISSUE THREAD

**Issue by hyaihjq** [matthiashar/CtCalib#2]
Hello, could you please share the test data? It would help in understanding the code better.

**Comment by matthiashar** [comment]
One of the data sets was now uploaded. See https://github.com/matthiashar/CtCalib/blob/main/README.md#example-data 
To use this data it has to be converted to a format that OpenCV can read.

**Comment by hyaihjq** [comment]
> One of the data sets was now uploaded. See https://github.com/matthiashar/CtCalib/blob/main/README.md#example-data To use this data it has to be converted to a format that OpenCV can read.

thanks for your replay, i try it.
